services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_portfolio
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./entrust:/etc/nginx/ssl # Mount the SSL certificates
      # command: /bin/sh -c "chown -R www-data:www-data /var/www/html && nginx -g 'daemon off;'"
    command: /bin/sh -c "chown -R root:root /var/www/html && nginx -g 'daemon off;'"
    depends_on:
      - php
      - redis
    networks:
      - network_portfolio

  redis:
    image: "redis:alpine"
    container_name: redis_portfolio
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - ./src:/var/www/html
    networks:
      - network_portfolio

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php_portfolio
    volumes:
      - ./src:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - network_portfolio

  composer:
    image: composer:latest
    container_name: composer_portfolio
    depends_on:
      - php
    networks:
      - network_portfolio

networks:
  network_portfolio:
